defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "{epoch:03d}"
  monitor: "val/mean_fid"
  mode: "min"
  save_last: true
  every_n_epochs: 1
  save_top_k: 3
  enable_version_counter: false

model_summary:
  max_depth: -1
